version: '3'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis:/data

  users-db:
    image: postgres
    restart: always
    env_file:
      - ./users-db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api-gateway:
    build: ./api-gateway/
    ports:
      - 8080:8080
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway:/usr/src/app
    depends_on:
      - redis

  users-service:
    build: ./users-service/
    env_file:
      - ./users-service/.env
    depends_on:
      - users-db
 
