version: '3'

services:
  users-db:
    image: postgres
    restart: always
    volumes:
      - /postgres-data:/var/lib/postgresql/data

  api-gateway:
    image: 127.0.0.1:5000/api-gateway
    build: ./api-gateway/
    ports:
      - 8080:8080
    volumes:
      - /home/docker/.docker:/certs
  
  test-server:
    image: 127.0.0.1:5000/test-server
    build: ./test-server/
    deploy:
      labels: [api=/test-server]

  users-service:
    image: 127.0.0.1:5000/users-service
    build: ./users-service/
    depends_on:
      - users-db
    deploy:
      labels: [api=/user]
