version: 2
jobs:
  build:
    working_directory: ~/tmp

    environment:
      DB_DATABASE: tanglewood_test
      JWT_SECRET: alpaca

    docker:
      - image: circleci/node:10
      - image: rethinkdb:latest
        environment:
          name: tanglewood_test

    steps:
      - checkout

      - run: npm install

      - run: npm run db:seed

      - run: npm test
