version: 2
jobs:
  build:
    working_directory: ~/tmp

    docker:
      - image: circleci/node:10
      - image: rethinkdb:latest
        environment:
          name: tanglewood_test
          initial-password: test

    steps:
      - checkout

      - run: npm install

      - run: npm run db:seed

      - run:
          name: Run tests
          environment:
            DB_DATABASE: tanglewood_test
            DB_PASSWORD: test
            JWT_SECRET: alpaca
          command: npm test
